<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Data Upload | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Update and upload data using OBIS REST API">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/admin.css">

        <script src="/obis/js/scripts.js"></script>
        <script src="/obis/js/dataupload.js"></script>
    </head>
    
    <body>

        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            
                <select name="type" class="type" id="type" onchange="generateForm()">
                    <option selected value="POST">Upload Data</option>
                    <option value="PUT">Update Data</option>
                    <option value="DELETE">Delete Data</option>
                </select>

                <select name="table" class="table" id="table" onchange="generateForm()">
                    <option selected value="answers">BMI answers data</option>
                    <option value="locations">Locations data</option>
                    <option value="responses">Responses data</option>
                    <option value="breakouts">Breakouts data</option>
                    <option value="breakout_categories">Breakout Categories data</option>
                </select>

                <div id="formHere">
                    <form action="#" id="leForm" onsubmit="executeRequest();return false">
                      <label for="locationabbr">Location</label>
                      <input type="text" id="locationabbr" name="locationabbr" placeholder="CA"><br>
                      <label for="year_value">Year</label>
                      <input type="text" id="year_value" name="year_value" placeholder="2018"><br>
                      <label for="sample_size">Sample Size</label>
                      <input type="text" id="sample_size" name="sample_size" placeholder="1002"><br>
                      <label for="data_value_percentage">Data Value Percentage</label>
                      <input type="text" id="data_value_percentage" name="data_value_percentage" placeholder="40.9"><br>
                      <label for="confidence_limit_low">Confidence Limit Low</label>
                      <input type="text" id="confidence_limit_low" name="confidence_limit_low" placeholder="39.1"><br>
                      <label for="confidence_limit_high">Confidence Limit High</label>
                      <input type="text" id="confidence_limit_high" name="confidence_limit_high" placeholder="42.6"><br>
                      <label for="response_id">Response ID</label>
                      <input type="text" id="response_id" name="response_id" placeholder="RESP040"><br>
                      <label for="break_out_id">Breakout ID</label>
                      <input type="text" id="break_out_id" name="break_out_id" placeholder="SEX1"><br>
                      <label for="break_out_category_id">Breakout Category ID</label>
                      <input type="text" id="break_out_category_id" name="break_out_category_id" placeholder="CAT2"><br>
                      <input type="submit" value="Submit">
                    </form>    
                </div>
                <div id="outcome"> </div>
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
    
    </body>
    
</html>
