<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Login | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/login.css">

        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body>

        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            
            <div class="form-container">
                <form action="/obis/account/loginAction" method="post">
                    <label for="email" class="sr-only">Enter Email</label>
                    <input id="email" name="email" type="email" placeholder="Email" required>
                    
                    <label for="password" class="sr-only">Enter password</label>
                    <input id="password" name="password" type="password" placeholder="Password" required>
                    
                    <button type="submit">login</button>
                </form>
            </div>
            
            <div class="register-container">
                <a href="/obis/account/register"><div>register here</div></a>
            </div>
            
            <?php 
                if(isset($userIsLoggedIn))
                    if($userIsLoggedIn === true)
                    {
                        echo "<p>welcome {$user->getFirstname()}</p>";
                    }
                    else 
                        echo "failed login";
            ?>
            
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
    
    </body>
    
</html>
