<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Register | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/register.css">
        
        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body>
        
        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            
            <h4 class="fail-disclaimer">
                <?php 
                    if(isset($registerFailed))
                        if($registerFailed === true)
                            echo "Register failed.";
                ?>
            </h4>
        
            <div class="form-container">
                <form action="/obis/account/registerAction" method="post">
                    <label for="firstname" class="sr-only">Enter first name</label>
                    <input id="firstname" name="firstname" type="text" placeholder="First name" required>
                    
                    <label for="lastname" class="sr-only">Enter last name</label>
                    <input id="lastname" name="lastname" type="text" placeholder="Last name" required>
                    
                    <label for="email" class="sr-only">Enter email</label>
                    <input id="email" name="email" type="email" placeholder="Email" required>
                    
                    <label for="password" class="sr-only">Enter password</label>
                    <input id="password" name="password" type="password" placeholder="Password" required>
                    
                    <label for="confirm-password" class="sr-only">Confirm password</label>
                    <input id="confirm-password" name="confirm-password" type="password" placeholder="Confirm password" required>
                    
                    <button type="submit">register</button>
                </form>
            </div>
            
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
    
    </body>
    
</html>
