<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="author" content="Hîncean Bogdana-Ioana">
    <title>Obis</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link rel="icon" type="image/ico" href="/obis/images/placeholders/logo.png" />
    <link href="https://fonts.googleapis.com/css?family=Frank+Ruhl+Libre&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap" rel="stylesheet">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="/obis/css/index.css">
    <script src="/obis/js/scripts.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    
    <script type="text/javascript">
    google.charts.load('current', {'packages':['corechart']});
    //google.charts.setOnLoadCallback(drawChart);

    function drawChart(str) 
    {
      var xmlhttp = new XMLHttpRequest();
       var options = {
          title: 'My Daily Activities'
        };
    
    xmlhttp.onreadystatechange = function() 
    {
      console.log("test");
      if (this.readyState == 4 && this.status == 200) {
      console.log(this.responseText);
      var data = google.visualization.arrayToDataTable([
          ['Task', 'Hours per Day'],
          ['Work',     11],
          ['Eat',      2],
          ['Commute',  2],
          ['Watch TV', 2],
          ['Sleep',    7]
        ]);

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));

        chart.draw(data, options);

      }
    };

    xmlhttp.open("GET","http://localhost/obis/api/answers/year/"+str,true);
    xmlhttp.setRequestHeader("Authorization","Bearer "+ localStorage.getItem("JWT"));
    xmlhttp.send();
      }

    </script>

    <link rel="stylesheet" href="/obis/css/statistics.css">
 </head>

  <body>
    <header>
      <a href="/obis/home/index" ><img src="/obis/images/obis-logo.svg" alt="obis logo"></a>
      <nav>
          <ul class="nav-button-list">
              <li><a href="/obis/home/index" class="nav-button">Home</a></li>
              <li><a href="/obis/statistics/index" class="nav-button" style="color: #ffd524; font-weight: bolder">Statistics</a></li>
              <li><a href="/obis/home/aboutus" class="nav-button">About us</a></li>
              <li><a href="/obis/home/contact" class="nav-button">Contact</a></li>
          </ul>
          <button onclick="dropMenu()" class="nav-dropmenu"><img src="/obis/images/nav-dropmenu.svg" alt="navigation drop down menu button"></button>
      </nav>
<!--               php here-->
      <a href="/obis/account/login" class="auth">
          sign in
      </a>
  </header>
  <main>
    <article>
      <div id="piechart" style="width: 900px; height: 500px;"></div>


<select name="year" id="year" onchange="drawChart(this.value)">
  <option value="2011">2011</option>
  <option value="2012">2012</option>
  <option value="2013">2013</option>
  <option value="2014">2014</option>
  <option value="2015">2015</option>
  <option value="2016">2016</option>
  <option value="2017">2017</option>
  <option value="2018">2018</option>
</select>

<select name="location" id="location">
  <option value="AZ">Arizona</option>
  <option value="AL">Alabama</option>
  <option value="AK">Alaska</option>
</select>

<form>
  <input type="radio" id="byBMI" name="filter" value="byBMI">
  <label for="byBMI">Filter by BMI</label><br>
  <input type="radio" id="byCAT" name="filter" value="byCAT">
  <label for="byCAT">Filter by Category</label><br>
</form>

<select name="bmi" id="bmi">
  <option value="RESP039">Obese (BMI 30.0 - 99.8)</option>
  <option value="RESP040">Overweight (BMI 25.0-29.9)</option>
  <option value="RESP041">Normal Weight (BMI 18.5-24.9)</option>
  <option value="RESP042">Underweight (BMI 12.0-18.4)</option>
</select>

<select name="breakouts" id="breaks">
  <option value="AGE01">18-24</option>
  <option value="AGE02">25-34</option>
  <option value="AGE03">35-44</option>
  <option value="AGE04">45-54</option>
</select>







</main>
<footer>
  <div class="logos">
      <a href="https://info.uaic.ro"><img class="logo" src="/obis/images/fii-logo.png"></a>
  </div>
  
  <div class="links-container">
      <ul class="links">
          <li class="icon"><a href="https://github.com/hristodormihai/Obis"><img src="/obis/images/github-white.svg"></a>
      </ul>
  </div>
  
  <div class="bottom-footer">
      <p class="copyright">Copyright © 2020 Crisan Mihai</p>
      <div class="select-language">
          <label for="language-select">Language:</label>
          <select name="language" id="language-select">
              <option value="english">English</option>
              <option value="romanian">Romanian</option>
              <option value="french">French</option>
          </select>
      </div>
  </div> 
</footer>
  </body>

  
</html>