<footer>
    <div class="logos">
        <a href="https://info.uaic.ro">
            <img class="logo" src="/obis/images/fii-logo.png" alt="UAIC FII logo" />
        </a>
    </div>
    
    <ul class="links">
        <li class="icon">
            <a href="https://github.com/hristodormihai/Obis">
                <img src="/obis/images/github-white.svg" alt="github logo" />
            </a>
        </li>
    </ul>

    <div class="copyright">
        <p>Copyright © 2020 Crisan Mihai & Hristodor Minu-Mihail</p>
    </div>

    <div class="language">
        <label for="language-select">Language:</label>
        <select name="language" id="language-select">
            <option value="english">English</option>
            <option value="romanian">Romanian</option>
            <option value="french">French</option>
        </select>
    </div>
</footer>