<?php
    $style = "style=\"color: #ffd524; font-weight: bolder\"";
    $array = explode('/', $_SERVER['REQUEST_URI']);
    $page = end($array);
?>

<header>
    <a href="/obis/home/home">
        <object data="/obis/images/obis-logo.svg" type="image/svg+xml">Website LOGO</object> 
    </a>

    <nav class="dropdown">
        <div onclick="dropMenu()" class="nav-dropmenu">
            <div onclick="navIcon()" id="nav-icon">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <ul class="nav-button-list" id="headDrop">
            <li><a href="/obis/home/home" class="nav-button" <?php if($page == "home") echo $style; ?>>Home</a></li>
            <li><a href="/obis/home/statistics" class="nav-button" <?php if($page == "statistics") echo $style; ?>>Statistics</a></li>
            <li><a href="/obis/home/aboutus" class="nav-button" <?php if($page == "aboutus") echo $style; ?>>About us</a></li>
            <li><a href="/obis/home/contact" class="nav-button" <?php if($page == "contact") echo $style; ?>>Contact</a></li>
        </ul>
    </nav>

    <a href="/obis/account/user" class="auth">
        <?php
            echo isset($_SESSION['firstname']) ? $_SESSION['firstname'] : "LOG IN"
        ?>
    </a>
</header>