<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>About us | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/obis/css/about-us.css">
        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body>
        
        <header>
            <a href="/obis/home/index" ><img src="/obis/images/obis-logo.svg" alt="obis logo"></a>
            <nav>
                <ul class="nav-button-list">
                    <li><a href="/obis/home/index" class="nav-button">Home</a></li>
                    <li><a href="/obis/statistics/index" class="nav-button">STATISTICS</a></li>
                    <li><a href="/obis/home/aboutus" class="nav-button" style="color: #ffd524; font-weight: bolder">About us</a></li>
                    <li><a href="/obis/home/contact" class="nav-button">Contact</a></li>
                </ul>
                <button onclick="dropMenu()" class="nav-dropmenu"><img src="/obis/images/nav-dropmenu.svg" alt="navigation drop down menu button"></button>
            </nav>
            <!--               php here-->
            <a href="/obis/account/login" class="auth">
                sign in
            </a>
        </header>

        <main>
            <div class="title">
                <h2>who are we?</h2>      
                <p>Meet the creators of the application!</p>
            </div>
            <div class="descriptions">
                <section class="hristodor">
                   <img src="/obis/images/HMM.png">
                   <h3>HRISTODOR MINU-MIHAIL </h3>
                    <p>
                    Computer Science student, passionate about information security and penetration testing.
                    Currently working as a Security Researcher at BitDefender for over a year.
                    Efficient in C++ and Python with projects finalised in Haskell, JavaScript, Java, C# and PHP.
                    </p>
                </section>
                <section class="crisan">
                    <img src="/obis/images/placeholders/logo.png">
                    <h3>CRISAN MIHAI</h3>
                    <p>
                    Fresh resident of Iasi and soon to be alumni of "Alexandru Ioan Cuza" University of Iasi 🤓.
                    My hobbies consist of clothing and technology.
                    I've been captivated by technology ever since I had my first experience with a computer and mobile phone,
                    from then on I was always interested in the latest and greatest advancements in this domain.
                    I've always been attracted by well built products and this makes me aspire to be a good software developer,
                    hopefully that dream will one day become a reality!
                    </p>
                </section>
        </main>
        
        <footer>
           <div class="logos">
            <a href="https://info.uaic.ro"><img class="logo" src="/obis/images/fii-logo.png" alt="UAIC FII logo"></a>
            </div>
            
            <div class="links-container">
                <ul class="links">
                    <li class="icon"><a href="https://github.com/hristodormihai/Obis"><img src="/obis/images/github-white.svg" alt="github logo"></a>
                </ul>
            </div>
            
            <div class="bottom-footer">
                <p class="copyright">Copyright © 2020 Crisan Mihai</p>
                <div class="select-language">
                    <label for="language-select">Language:</label>
                    <select name="language" id="language-select">
                        <option value="english">English</option>
                        <option value="romanian">Romanian</option>
                        <option value="french">French</option>
                    </select>
                </div>
            </div> 
        </footer>
        
    </body>
    
</html>
