<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="robots" content="noindex">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/obis/css/about-us.css">
        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body>
        
        <header>
            <a href="/obis/home/index" ><img src="/obis/images/obis-logo.svg" alt="obis logo"></a>
            <nav>
                <ul class="nav-button-list">
                    <li><a href="/obis/home/index" class="nav-button">Home</a></li>
                    <li><a href="/obis/statistics/index" class="nav-button">STATISTICS</a></li>
                    <li><a href="/obis/home/aboutus" class="nav-button" style="color: #ffd524; font-weight: bolder">About us</a></li>
                    <li><a href="/obis/home/contact" class="nav-button">Contact</a></li>
                </ul>
                <button onclick="dropMenu()" class="nav-dropmenu"><img src="/obis/images/nav-dropmenu.svg" alt="navigation drop down menu button"></button>
            </nav>
            <!--               php here-->
            <a href="/obis/account/login" class="auth">
                sign in
            </a>
        </header>

        <main>
            
            <div class="title">
                <h2>who are we?</h2>      
                <p>Meet the creators of the application!</p>
            </div>
            <div class="descriptions">
                <section class="hristodor">
                   <img src="/obis/images/HMM.png">
                   <h3>HRISTODOR MINU-MIHAIL </h3>
                    <p>Computer Science student, passionate about infosec and pentesting. Currently working as a Security Researcher at BitDefender for over an year. Efficient in C++ and Python with projects finalised in Haskell, JavaScript, Java, C# and PHP.</p></section>
                <section class="crisan">
                    <img src="/obis/images/placeholders/logo.png">
                    <h3>CRISAN MIHAI</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam nulla dolor libero quasi provident unde doloribus architecto odit recusandae. Quidem eveniet, nihil reprehenderit enim, necessitatibus corporis, tempore adipisci sed maiores commodi perferendis quaerat dicta voluptate amet, cupiditate ducimus laborum debitis unde officiis repellat veniam quis optio quae excepturi! Dolorum, culpa officiis harum ullam ut autem? Saepe ex consequatur aperiam amet repellat sed id debitis deleniti consectetur doloremque, molestiae qui quo perspiciatis maiores sapiente temporibus ipsa quibusdam! Dolorum sit quasi quod amet officia porro modi accusamus veniam consequuntur? Minus fuga mollitia corporis, at, molestiae est quisquam recusandae unde, quae illo fugiat.</p>
                </section>
            </article>
                        
        </main>
        
        <footer>
           <div class="logos">
            <a href="https://info.uaic.ro"><img class="logo" src="/obis/images/fii-logo.png" alt="UAIC FII logo"></a>
            </div>
            
            <div class="links-container">
                <ul class="links">
                    <li class="icon"><a href="https://github.com/hristodormihai/Obis"><img src="/obis/images/github-white.svg" alt="github logo"></a>
                </ul>
            </div>
            
            <div class="bottom-footer">
                <p class="copyright">Copyright © 2020 Crisan Mihai</p>
                <div class="select-language">
                    <label for="language-select">Language:</label>
                    <select name="language" id="language-select">
                        <option value="english">English</option>
                        <option value="romanian">Romanian</option>
                        <option value="french">French</option>
                    </select>
                </div>
            </div> 
        </footer>
        
    </body>
    
</html>
