<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>About us | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/aboutus.css">

        <script>
            loginButtonName = `<?php echo isset($_SESSION['firstname']) ? $_SESSION['firstname'] : "LOG IN" ?>`
        </script>
        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body onresize="leSizeCheck()">
        
        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->

        <main>
            <div class="title">
                <h2>who are we?</h2>      
                <p>Meet the creators of the application!</p>
            </div>
            <div class="descriptions">
                <section class="hristodor">
                   <img src="/obis/images/HMM.png" alt="Photo of Hristodor Minu-Mihail">
                   <h3>HRISTODOR MINU-MIHAIL </h3>
                    <p>
                    Computer Science student, passionate about information security and penetration testing.
                    Currently working as a Security Researcher at BitDefender for over a year.
                    Efficient in C++ and Python with projects finalised in Haskell, JavaScript, Java, C# and PHP.
                    </p>
                </section>
                <section class="crisan">
                    <img src="/obis/images/placeholders/logo.png" alt="Photo of Crisan Mihai">
                    <h3>CRISAN MIHAI</h3>
                    <p>
                    Fresh resident of Iasi and soon to be alumni of "Alexandru Ioan Cuza" University of Iasi 🤓.
                    My hobbies consist of clothing and technology.
                    I've been captivated by technology ever since I had my first experience with a computer and mobile phone,
                    from then on I was always interested in the latest and greatest advancements in this domain.
                    I've always been attracted by well built products and this makes me aspire to be a good software developer,
                    hopefully that dream will one day become a reality!
                    </p>
                </section>
            </div>
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
        
    </body>
    
</html>
