<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Contact | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/contact.css">

        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body>
        
        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            
            <h2>Have a question? Contact us!</h2>
            <div class="form-container">
                <form action="/obis/home/contact" method="post">
                    <label for="name" class="sr-only">Enter name</label>
                    <input id="name" name="name" type="text" placeholder="Name" required>
                    
                    <label for="email" class="sr-only">Enter email</label>
                    <input id="email" name="email" type="email" placeholder="Email" required>
                    
                    <label for="message" class="sr-only">Enter your message</label>
                    <textarea id="message" name="message" rows="10" placeholder="Message" required></textarea>
                    
                    <button type="submit">send message</button>
                </form>
            </div>
            
            <h2>or meet us in person!</h2>
            <p>according to the specified timeframes</p>
            <div class="table-container">
                <table>
                    <caption>
                        Our schedule
                    </caption>
                    <thead>
                        <tr>
                            <th></th>
                            <th scope="col">Mon</th>
                            <th scope="col">Tue</th>
                            <th scope="col">Wed</th>
                            <th scope="col">Thu</th>
                            <th scope="col">Fri</th>
                            <th scope="col">Sat</th>
                            <th scope="col">Sun</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">08:00-10:00</th>
                            <td class="red-bg">✖</td>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="green-bg">✓</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                        <tr>
                            <th scope="row">10:00-12:00</th>
                            <td class="green-bg">✓</td>
                            <td class="green-bg">✓</td>
                            <td class="green-bg">✓</td>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                        <tr>
                            <th scope="row">12:00-14:00</th>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                        <tr>
                            <th scope="row">14:00-16:00</th>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                        <tr>
                            <th scope="row">16:00-18:00</th>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                        <tr>
                            <th scope="row">18:00-20:00</th>
                            <td class="green-bg">✓</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg">✖</td>
                            <td class="red-bg" colspan="2">✖</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        
                    </tfoot>
                </table>
            </div>

           <div class="iframe-container">
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d796.694484088856!2d27.574196340406306!3d47.17395975288563!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40cafb6227e846bd%3A0x193e4b6864504e2c!2sFaculty%20of%20Computer%20Science!5e0!3m2!1sen!2sro!4v1587606085710!5m2!1sen!2sro" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
           </div>

        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
        
    </body>
    
</html>