<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Homepage | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/home.css">

        <script src="/obis/js/scripts.js.php"></script>
    </head>
    
    <body onresize="leSizeCheck()">
        
        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            <article>
                <div class="content">
                   <h3>About the application</h3>
                    <p>
                    Obis is an application that let's you view and access statistics about obesity in the United States.
                    Data is collected by telephone surveys, the data is provided by Behavioral Risk Factor Surveillance System (BRFSS).
                    <br />
                    Aside from just viewing statistics about a single state, the web application allows you to compare the statistics of two states of choice
                    using a column chart, it as well as includes a map of the United States that encompasses statistics about every state.
                    The chosen statistics can be saved locally in any of these formats:
                    </p>
                    <ul>
                        <li>SVG</li>
                        <li>WEBP</li>
                        <li>CSV</li>
                    </ul>

                    <h3>Calculate your BMI here</h3>
                    <br>
                    <iframe src="https://bmicalculatorireland.com/widgets/widget.php?t=720x300" width="720" height="300" frameborder="0"></iframe><p style="font-family: sans-serif; font-size: 14px">Supplied by <a style="color: #3d4195;" href="https://bmicalculatorireland.com">BMI Calculator Ireland</a></p>
                </div>
            </article>            
            <aside class="aside-container">
               <p class="aside-p">Related pages</p>
                <ul>
                    <li><a href="https://www.cdc.gov/brfss/annual_data/annual_data.htm">BRFSS data</a></li>
                    <li><a href="https://chronicdata.cdc.gov/d/dttw-5yxu/visualization">CDC's visualizer tool</a></li>
                    <li><a href="https://chronicdata.cdc.gov/resource/dttw-5yxu.json">CDC's API endpoint</a></li>
                </ul>
            </aside>                
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
        
    </body>
    
</html>
