<!DOCTYPE html>

<html lang="en">
    
    <head>
        <title>Homepage | Obis</title>
        <meta charset="utf-8">
        <meta name="description" content="Visualise BRFSS adult obesity statistics and access our REST API.">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/home.css">

        <script>
            loginButtonName = `<?php echo isset($_SESSION['firstname']) ? $_SESSION['firstname'] : "LOG IN" ?>`
        </script>
        <script src="/obis/js/scripts.js"></script>
    </head>
    
    <body onresize="leSizeCheck()">
        
        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->
        
        <main>
            <article>
                <div class="content">
                   <h3>About the application</h3>
                    <p>
                    Obis is an application that let's you view and access statistics about obesity in the United States.
                    Data is collected by telephone surveys, the data is provided by Behavioral Risk Factor Surveillance System (BRFSS).
                    <br />
                    Aside from just viewing statistics about a single state, the web application allows you to compare the statistics of two states of choice
                    using a column chart, it as well as includes a map of the United States that encompasses statistics about every state.
                    The chosen statistics can be saved locally in any of these formats:
                    </p>
                    <ul>
                        <li>SVG</li>
                        <li>WEBP</li>
                        <li>CSV</li>
                    </ul>

                    <h3>Calculate your BMI</h3>
                    <p>Compare your <span class="bold underline">B</span>ody <span class="bold underline">M</span>ass <span class="bold underline">I</span>ndex with the ones from the statistics page! Start by calculating your BMI using the tool below:</p>
                    <div class="calculator">
                        <iframe src="https://bmicalculatorireland.com/widgets/widget.php?t=300x300" width="300" height="300" title="BMI Calculator"></iframe>
                        <p>Supplied by <a href="https://bmicalculatorireland.com" class="inline-link">BMI Calculator Ireland</a></p>
                    </div>
                    <p>After you calculated your body mass index, head over to the <a href="/obis/home/statistics" class="inline-link">statistics</a> page and compare your index with thousands of others from the United States of America!</p>
                </div>
            </article>            
            <aside class="aside-container">
               <p class="aside-p">Related pages</p>
                <ul>
                    <li><a href="https://www.cdc.gov/brfss/annual_data/annual_data.htm"><p>BRFSS data</p></a></li>
                    <li><a href="https://chronicdata.cdc.gov/d/dttw-5yxu/visualization"><p>CDC's visualizer tool</p></a></li>
                    <li><a href="https://chronicdata.cdc.gov/resource/dttw-5yxu.json"><p>CDC's API endpoint</p></a></li>
                </ul>
            </aside>                
        </main>
        
        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->
        
    </body>
    
</html>
