<!DOCTYPE html>

<html lang="en">

    <head>
        <title>View statistics | Obis</title>
        <meta charset="utf-8">
        <meta name="author" content="Hristodor Minu-Mihail">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="icon" type="image/ico" href="/obis/images/placeholders/logo.png" />
        <link rel="stylesheet" href='https://fonts.googleapis.com/css?family=Montserrat'>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Frank+Ruhl+Libre&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap">
        <link rel="stylesheet" href="/obis/css/allpages.css">
        <link rel="stylesheet" href="/obis/css/statistics.css">

        <script src="/obis/js/scripts.js"></script>
        <script src="https://www.gstatic.com/charts/loader.js"></script>
        <script src="/obis/js/statistics.js" type="text/javascript"></script>
    </head>

    <body>

        <!-- HEADER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "header.phtml"; ?>
        <!-- HEADER -->

        <main>
            <!-- START PIECHART -->
            <div class="sector">
                <div id="piechart" class="drawspace"></div>
                
                <div class="options">
                    <div class="labels">
                        <label for="year">Year</label>
                        <label for="location">Location</label>
                        <label for="filterType">Filter by</label>
                        <label for="bmi" id="leBMIch1">Choose BMI</label>
                        <label for="cat">Choose category</label>
                        <label for="breaks" id="leBreakch1" class="show">Choose break out</label>
                    </div>
                    
                    <div class="selects">
                        <div class="option">
                            <select name="year" id="year" onchange="drawChart()">
                                <?php
                                    foreach($yearsArray as $year)
                                    echo "<option value=\"$year\">$year</option>"
                                    ?>
                            </select>
                        </div>
                        
                        <div class="option">
                            <select name="location" class="location" id="location" onchange="drawChart()">
                                <?php
                                    foreach($statesArray as $stateAbbr => $state)
                                    echo "<option value=\"$stateAbbr\">$state</option>"
                                ?>
                            </select>
                        </div>
                        
                        <div class="option">
                            <select name="typeFilter" id="filterType" onchange="drawChart(); hideOther(this.id);">
                                <option selected value="byBMI">BMI</option>
                                <option value="byCAT">Category</option>
                            </select>
                        </div>
                        
                        <div class="option">    
                            <select name="bmi" id="bmi" onchange="drawChart()">
                                <option selected value="RESP039">Obese (BMI 30.0 - 99.8)</option>
                                <option value="RESP040">Overweight (BMI 25.0-29.9)</option>
                                <option value="RESP041">Normal Weight (BMI 18.5-24.9)</option>
                                <option value="RESP042">Underweight (BMI 12.0-18.4)</option>
                            </select>
                        </div>
                        
                        <div class="option">
                            <select name="breaks_cat" id="cat" onchange="setCategory(this.value,this.id)">
                                <option value="CAT2">Gender</option>
                                <option selected value="CAT3">Age Group</option>
                                <option value="CAT4">Race/Ethnicity</option>
                                <option value="CAT5">Education Attained</option>
                                <option value="CAT6">Household Income</option>
                            </select>
                        </div>
                        
                        <div id="shape_shifter" class="option show">
                            <select name="breakouts" id="breaks" onchange="drawChart()">
                                <option selected value="AGE01">18-24</option>
                                <option value="AGE02">25-34</option>
                                <option value="AGE03">35-44</option>
                                <option value="AGE04">45-54</option>
                                <option value="AGE05">55-64</option>
                                <option value="AGE09">65+</option>
                            </select>
                        </div>
                    </div>
                </div>
                    
                <div class="export">
                    <label for="exp1">Export as</label>
                    <div class="select-wrapper">
                        <select name="export" id="exp1">
                            <option value="svg">SVG</option>
                            <option value="csv">CSV</option>
                            <option value="webp">WEBP</option>
                        </select>
                        <button type="button" id="expBtn1" onclick="exportData(this.id)">Export</button>
                    </div>
                </div>
            </div>
            <!-- END PIECHART -->
            
            <div class="separator"></div>

            <!-- START COLUMNCHART -->
            <div class="sector">
                <div id="columnchart" class="drawspace"></div>

                <div class="options">
                    <div class="labels">
                        <label for="year2">Year</label>
                        <label for="location2">Location 1</label>
                        <label for="location3">Location 2</label>
                        <label for="filterType2">Filter by</label>
                        <label for="bmi2" id="leBMIch2">Choose BMI</label>
                        <label for="cat2">Choose category</label>
                        <label for="breaks2" id="leBreakch2" class="show">Choose break out</label>
                    </div>

                    <div class="selects">
                        <div class="option">
                            <select name="year" id="year2" onchange="drawColumn()">
                                <?php
                                    for($i = 2011; $i <= 2018; $i++)
                                        echo "<option value=\"$i\">$i</option>"
                                ?>
                            </select>
                        </div>

                        <div class="option">
                            <select name="location" class="location" id="location2" onchange="drawColumn()">
                                <?php
                                    foreach($statesArray as $stateAbbr => $state)
                                    echo "<option value=\"$stateAbbr\">$state</option>"
                                ?>
                            </select>
                        </div>

                        <div class="option">
                            <select name="location" class="location" id="location3" onchange="drawColumn()">
                                <?php
                                    foreach($statesArray as $stateAbbr => $state)
                                    echo "<option value=\"$stateAbbr\">$state</option>"
                                ?>
                            </select>
                        </div>

                        <div class="option">
                            <select name="typeFilter" id="filterType2" onchange="drawColumn(); hideOther(this.id)">
                                <option selected value="byBMI">Filter by BMI</option>
                                <option value="byCAT">Filter by Category</option>
                            </select>
                        </div>

                        <div class="option">
                            <select name="bmi" id="bmi2" onchange="drawColumn()">
                            <option selected value="RESP039">Obese (BMI 30.0 - 99.8)</option>
                            <option value="RESP040">Overweight (BMI 25.0-29.9)</option>
                            <option value="RESP041">Normal Weight (BMI 18.5-24.9)</option>
                            <option value="RESP042">Underweight (BMI 12.0-18.4)</option>
                            </select>
                        </div>

                        <div class="option">
                            <select name="breaks_cat" id="cat2" onchange="setCategory(this.value,this.id)">
                                <option value="CAT2">Gender</option>
                                <option selected value="CAT3">Age Group</option>
                                <option value="CAT4">Race/Ethnicity</option>
                                <option value="CAT5">Education Attained</option>
                                <option value="CAT6">Household Income</option>
                            </select>
                        </div>

                        <div id="shape_shifter2" class="option show">
                            <select name="breakouts" id="breaks2" onchange="drawColumn()">
                                <option selected value="AGE01">18-24</option>
                                <option value="AGE02">25-34</option>
                                <option value="AGE03">35-44</option>
                                <option value="AGE04">45-54</option>
                                <option value="AGE05">55-64</option>
                                <option value="AGE09">65+</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="export">
                    <label for="exp2">Export as</label>
                    <div class="select-wrapper">
                        <select name="export" id="exp2">
                            <option selected value="svg">SVG</option>
                            <option value="webp">WEBP</option>
                            <option value="csv">CSV</option>
                        </select>
                        <button type="button" id="expBtn2" onclick="exportData(this.id)">Export</button>
                    </div>
                </div>
            </div>
            <!-- END COLUMNCHART -->

            <div class="separator"></div>

            <!-- START MAP -->
            <div class="sector">
                <div>
                    <div id="mapTitle"> </div>
                    <div id="map" class="drawspace"></div>
                </div>

                <div class="options">
                    <div class="labels">
                        <label for="year3">Year</label>
                        <label for="bmi3">Choose BMI</label>
                        <label for="cat3">Choose category</label>
                        <label for="breaks3">Choose break out</label>
                    </div>

                    <div class="selects">
                        <div class="option">
                            <select name="year" id="year3" onchange="drawMap()">
                                <?php
                                    for($i = 2011; $i <= 2018; $i++)
                                        echo "<option value=\"$i\">$i</option>"
                                ?>
                            </select>
                        </div>
                        
                        <div class="option">
                            <select name="bmi" id="bmi3" onchange="drawMap()">
                                <option selected value="RESP039">Obese (BMI 30.0 - 99.8)</option>
                                <option value="RESP040">Overweight (BMI 25.0-29.9)</option>
                                <option value="RESP041">Normal Weight (BMI 18.5-24.9)</option>
                                <option value="RESP042">Underweight (BMI 12.0-18.4)</option>
                            </select>
                        </div>
                            
                        <div class="option">
                            <select name="breaks_cat" id="cat3" onchange="setCategory(this.value,this.id)">
                                <option value="CAT2">Gender</option>
                                <option selected value="CAT3">Age Group</option>
                                <option value="CAT4">Race/Ethnicity</option>
                                <option value="CAT5">Education Attained</option>
                                <option value="CAT6">Household Income</option>
                            </select>
                        </div>
                            
                        <div id="shape_shifter3" class="option">
                            <select name="breakouts" id="breaks3" onchange="drawMap()">
                                <option selected value="AGE01">18-24</option>
                                <option value="AGE02">25-34</option>
                                <option value="AGE03">35-44</option>
                                <option value="AGE04">45-54</option>
                                <option value="AGE05">55-64</option>
                                <option value="AGE09">65+</option>
                            </select>
                        </div>
                    </div>
                </div>

                <div class="export">
                    <label for="exp3">Export as</label>
                    <div class="select-wrapper">
                        <select name="export" id="exp3">
                            <option selected value="svg">SVG</option>
                            <option value="webp">WEBP</option>
                            <option value="csv">CSV</option>
                        </select>
                        <button type="button" id="expBtn3" onclick="exportData(this.id)">Export</button>
                    </div>
                </div>
            </div>
            <!-- END MAP -->
        </main>

        <!-- FOOTER -->
        <?php include "app" . DIRECTORY_SEPARATOR . "views" . DIRECTORY_SEPARATOR . "footer.phtml"; ?>
        <!-- FOOTER -->

    </body>

</html>